package stateplan

import (
    "fmt"
    "sort"
    "strings"

    "github.com/your-org/terraform-mcp-analyzer/internal/engine"
)

// Op mirrors engine.State for convenience.
type Op struct {
    Op   string // rm|mv
    Addr string
    To   string // for mv
}

// FromFindings flattens state actions from findings.
func FromFindings(findings []engine.Finding) []Op {
    var ops []Op
    for _, f := range findings {
        for _, s := range f.State {
            ops = append(ops, Op{Op: s.Op, Addr: s.Addr, To: s.To})
        }
    }
    // Deterministic: rm before mv; then by addr
    sort.SliceStable(ops, func(i, j int) bool {
        if ops[i].Op != ops[j].Op { return ops[i].Op < ops[j].Op }
        return ops[i].Addr < ops[j].Addr
    })
    return ops
}

// RenderScript renders a safe shell script for state migration.
func RenderScript(ops []Op) string {
    var b strings.Builder
    b.WriteString("#!/usr/bin/env bash\nset -euo pipefail\n")
    if len(ops) == 0 {
        b.WriteString("# No state operations required\n")
        return b.String()
    }
    b.WriteString("# Terraform state migration generated by terraform-mcp-analyzer\n")
    for _, op := range ops {
        switch op.Op {
        case "rm":
            b.WriteString(fmt.Sprintf("terraform state rm %s\n", shellEscape(op.Addr)))
        case "mv":
            b.WriteString(fmt.Sprintf("terraform state mv %s %s\n", shellEscape(op.Addr), shellEscape(op.To)))
        }
    }
    return b.String()
}

func shellEscape(s string) string {
    if strings.IndexFunc(s, func(r rune) bool { return r == ' ' || r == '"' || r == '\'' }) >= 0 {
        return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
    }
    return s
}
